#pragma once

#define TRANSFORMERS_FUSION_VERSION_MAJOR 1
#define TRANSFORMERS_FUSION_VERSION_MINOR 1
#define TRANSFORMERS_FUSION_VERSION_PATCH 0
#define TRANSFORMERS_FUSION_VERSION_STRING "R0001.01"
#define TRANSFORMERS_FUSION_BUILD_DATE __DATE__
#define TRANSFORMERS_FUSION_BUILD_TIME __TIME__
